Projeto.Web/Controllers/LivroController.cs
using Newtonsoft.Json;
using Projeto.Data.Entities;
using Projeto.Util;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;
namespace Projeto.Web.Controllers
{
    public class LivroController : Controller
    {
        public ActionResult Pesquisa()
        {
            return View();
        }

        [HttpGet]
        public ActionResult PesquisarLivros(string q)
        {
            var usuario = (Usuario)Session["usuariologado"];

            if (usuario == null)
            {
                ViewBag.Resultados = new List<dynamic>();
                ViewBag.Mensagem = "Usuário não está logado.";
                return View("Pesquisa");
            }

            if (string.IsNullOrEmpty(usuario.ApiKey))
            {
                ViewBag.Resultados = new List<dynamic>();
                ViewBag.Mensagem = "Você precisa cadastrar uma Chave de API primeiro.";
                return View("Pesquisa");
            }

            if (string.IsNullOrEmpty(q))
            {
                ViewBag.Resultados = new List<dynamic>();
                ViewBag.Mensagem = "Digite algum termo para pesquisar.";
                return View("Pesquisa");
            }

            try
            {
                string apiKey = Criptografia.Descriptografar(usuario.ApiKey);
                string url = $"https://www.googleapis.com/books/v1/volumes?q={q}&maxResults=9&key={apiKey}";

                using (var client = new HttpClient())
                {
                    var response = client.GetAsync(url).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        var json = response.Content.ReadAsStringAsync().Result;
                        dynamic dados = JsonConvert.DeserializeObject(json);

                        if (dados.items != null)
                        {
                            ViewBag.Resultados = dados.items;
                            ViewBag.Mensagem = null; 
                        }
                        else
                        {

                            ViewBag.Resultados = new List<dynamic>();
                            ViewBag.Mensagem = "A consulta digitada está incorreta ou a Chave de API está incorreta.";
                        }
                    }
                    else
                    {
                        ViewBag.Resultados = new List<dynamic>();
                        ViewBag.Mensagem = "Erro ao acessar a API do Google Books. Verifique sua Chave de API.";
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Resultados = new List<dynamic>();
                ViewBag.Mensagem = "Erro: " + ex.Message;
            }

            return View("Pesquisa");
        }
    }
}

Projeto.Web/Controllers/UsuarioController.cs
using Projeto.Data.Entities;
using Projeto.Data.Persistence;
using Projeto.Util;
using Projeto.Web.Models;
using System;
using System.Configuration;
using System.Data.SqlClient;
using System.Web.Mvc;
using System.Web.Security;
namespace Projeto.Web.Controllers
{
    [AllowAnonymous]
    public class UsuarioController : Controller
    {
        public ActionResult Cadastro()
        {
            return View(); 
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult CadastroChave()
        {
            return PartialView("_CadastroChave", new ChaveApiCadastroModel());
        }

        [HttpPost]
        public ActionResult AutenticarUsuario(UsuarioModelLogin model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UsuarioData d = new UsuarioData(); 
                    Usuario u = d.Authenticate(model.Login,
                    Criptografia.GetMD5Hash(model.Senha));
                    if (u != null) 
                    {
                        FormsAuthentication.SetAuthCookie(u.Email, false);

                        Session.Add("usuariologado", u);
                        return RedirectToAction("Index", "Biblioteca");
                    }
                    else 
                    {
                        ViewBag.Mensagem = "Acesso Negado.";
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Mensagem = e.Message;
                }
            }
            return View("Login"); 
        }

        [HttpPost]
        public ActionResult CadastrarUsuario(UsuarioModelCadastro model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Usuario u = new Usuario() 
                    {
                        Nome = model.Nome,
                        Email = model.Email,
                        Senha = Criptografia.GetMD5Hash(model.Senha),
                        DataCadastro = DateTime.Now
                    };
                    UsuarioData d = new UsuarioData();
                    d.Insert(u); 
                    ViewBag.Mensagem = "Usuario " + u.Nome + ", cadastrado com sucesso.";
                    ModelState.Clear(); 
                }
                catch (Exception e)
                {
                    ViewBag.Mensagem = e.Message;
                }
            }
            return View("Cadastro"); 
        }

        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Remove("usuariologado");
            Session.Abandon();
            return View("Login");
        }

        [HttpPost]
        public JsonResult CadastroChave(ChaveApiCadastroModel model)
        {
            var resultado = new { sucesso = false, mensagem = "" };

            if (ModelState.IsValid)
            {
                try
                {
                    var usuario = (Usuario)Session["usuariologado"];
                    if (usuario == null)
                    {
                        resultado = new { sucesso = false, mensagem = "Usuário não está logado." };
                        return Json(resultado);
                    }

                    string chaveCriptografada = Criptografia.Criptografar(model.ApiKey);

                    string connectionString = ConfigurationManager.ConnectionStrings["banco"].ConnectionString;

                    using (SqlConnection conn = new SqlConnection(connectionString))
                    {
                        conn.Open();
                        string sql = "UPDATE Usuario SET ApiKey = @ApiKey WHERE Id = @Id";

                        using (SqlCommand cmd = new SqlCommand(sql, conn))
                        {
                            cmd.Parameters.AddWithValue("@ApiKey", chaveCriptografada);
                            cmd.Parameters.AddWithValue("@Id", usuario.Id);

                            int linhasAfetadas = cmd.ExecuteNonQuery();

                            if (linhasAfetadas > 0)
                            {
                                usuario.ApiKey = chaveCriptografada;
                                Session["usuariologado"] = usuario;

                                resultado = new { sucesso = true, mensagem = "Chave Api " + usuario.Nome + " cadastrada/atualizada com sucesso." };
                            }
                            else
                            {
                                resultado = new { sucesso = false, mensagem = "Usuário não encontrado no banco." };
                            }
                        }
                    }
                }
                catch (Exception e)
                {
                    resultado = new { sucesso = false, mensagem = "Erro: " + e.Message };
                }
            }
            else
            {
                resultado = new { sucesso = false, mensagem = "Dados inválidos." };
            }

            return Json(resultado);
        }
    }
}

Projeto.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Projeto Cadastro de Entretenimento</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/login-cadastro.css" rel="stylesheet" />
</head>
<body>
    <div class="well">
        <h2>Projeto de Cadastro de Livros</h2>
        @RenderSection("subtitulo", required: false)
    </div>
    @RenderBody()

    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</body>
</html>

Projeto.Web/Views/Shared/_LayoutLogado.cshtml
@using Projeto.Data.Entities
@{ Usuario u = (Usuario)Session["usuariologado"]; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Projeto Cadastro de Entretenimento</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/index-estilo.css" rel="stylesheet" />
    <link href="~/Content/pesquisa-estilo.css" rel="stylesheet" />
    <link href="~/Content/dropdown-estilo.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <div class="well">
        <div class="projeto">
            <h2><span>@u.Nome</span></h2>
        </div>
        <div class="top-buttons">
            <div class="btn-menu dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="btnEngrenagem" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-gear-fill"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="btnEngrenagem">
                    <li><a class="dropdown-item" href="@Url.Action("Index", "Biblioteca")">Minhas Bibliotecas</a></li>
                    <li><a class="dropdown-item" href="@Url.Action("Pesquisa", "Livro")">Pesquisar Livros</a></li>
                    <li><a class="dropdown-item" id="btnAbrirCadastroChaveDropdown" href="#">Cadastrar / Atualizar Chave API</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>@Html.ActionLink("Sair do Sistema", "Logout", "Usuario", null, new { @class = "dropdown-item" })</li>
                </ul>
            </div>
        </div>
    </div>


    <div id="containerModalChave"></div>

    @RenderSection("subtitulo", required: false)
    @RenderBody()


    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/modal-biblioteca.js"></script> 
    <script src="~/Scripts/adicionar-chave.js"></script>
    <script>
        var urlGetCadastroChave = '@Url.Action("CadastroChave","Usuario")';
        var urlPostCadastroChave = '@Url.Action("CadastroChave","Usuario")';
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>